// Generated by data/music-catalog/generate_public_music_data.py. Do not edit.
window.MUSIC_DATA = [
  { title:'Adiós Amor (Versión Bolero)', artist:'Luis Guinea', role:'Artist', artwork:'Adiós-Amor-Versión-Bolero---Luis-Guinea.webp', releaseType:'Single', year:2020, roles:['Artist', 'Producer'], preview:null },
  { title:'Hasta Que Lleguemos Al Mar', artist:'Luis Guinea, Tony Barhoum', role:'Artist', artwork:'Hasta-Que-Lleguemos-Al-Mar---Luis-Guinea.webp', releaseType:'Single', year:2024, roles:['Artist'], preview:'hasta-que-lleguemos-al-mar--luis-guinea--2024.mp3' },
  { title:'Hace Tanto Tiempo', artist:'Luis Guinea', role:'Artist', artwork:'Hace-Tanto-Tiempo---Luis-Guinea.webp', releaseType:'Single', year:2021, roles:['Artist'], preview:'hace-tanto-tiempo--luis-guinea--2021.mp3' },
  { title:'Blue Moon', artist:'Luis Guinea', role:'Composer', artwork:'Blue-Moon---Luis-Guinea.webp', releaseType:'Single', year:2015, roles:['Songwriter', 'Artist', 'Producer'], preview:null },
  { title:'Volver a Verte', artist:'Luis Guinea', role:'Artist', artwork:'Volver-a-Verte---Luis-Guinea.webp', releaseType:'Single', year:2020, roles:['Artist'], preview:'volver-a-verte--luis-guinea--2020.mp3' },
  { title:'Cómo Decirte', artist:'Luis Guinea, Pablo Delgado', role:'Producer', artwork:'Cómo-Decirte---Luis-Guinea.webp', releaseType:'Single', year:2022, roles:['Artist', 'Songwriter', 'Producer'], preview:'como-decirte--luis-guinea--2022.mp3' },
  { title:'Nuestro Hogar', artist:'Luis Guinea', role:'Artist', artwork:'Nuestro-Hogar---Luis-Guinea.webp', releaseType:'Single', year:2022, roles:['Artist'], preview:'nuestro-hogar--luis-guinea--2022.mp3' },
  { title:'12 Meses', artist:'Rogelio Edel', role:'Producer', artwork:'12-Meses---Rogelio-Edel.webp', releaseType:'Single', year:2022, roles:['Producer'], preview:'12-meses--rogelio-edel--2022.mp3' },
  { title:'La Bamba', artist:'Rogelio Edel', role:'Producer', artwork:'La-Bamba---Rogelio-Edel.webp', releaseType:'Single', year:2022, roles:['Producer'], preview:'la-bamba--rogelio-edel--2022.mp3' },
  { title:'A Escondidas', artist:'Isabella Macías', role:'Producer', artwork:'A-Escondidas---Isabella-Macías.webp', releaseType:'Single', year:2018, roles:['Producer'], preview:null },
  { title:'Lo Que Queda de Mí', artist:'Escala de Grises', role:'Producer', artwork:'Lo-Que-Queda-de-Mí---Escala-de-Grises.webp', releaseType:'Single', year:2016, roles:['Songwriter', 'Producer', 'Artist'], preview:null },
  { title:'Abrazo Imaginario', artist:'Ricardo Bojalil', role:'Producer', artwork:'Abrazo-Imaginario---Ricardo-Bojalil.webp', releaseType:'Single', year:2022, roles:['Songwriter', 'Producer', 'Recording Engineer'], preview:'abrazo-imaginario--ricardo-bojalil--2022.mp3' },
  { title:'Shape of You - Acoustic', artist:'Segundo Piso', role:'Producer', artwork:'Shape-of-You---Acoustic---Segundo-Piso.webp', releaseType:'Single', year:2017, roles:['Producer'], preview:null }
];
