// Generated by data/music-catalog/generate_public_music_data.py. Do not edit.
window.MUSIC_DATA = [
  { title:'Hasta Que Lleguemos Al Mar', artist:'Luis Guinea, Tony Barhoum', role:'Artist', artwork:'Hasta-Que-Lleguemos-Al-Mar---Luis-Guinea.webp', releaseType:'Single', year:2024, roles:['Artist'], preview:'hasta-que-lleguemos-al-mar--luis-guinea--2024.mp3' },
  { title:'Hace Tanto Tiempo', artist:'Luis Guinea', role:'Artist', artwork:'Hace-Tanto-Tiempo---Luis-Guinea.webp', releaseType:'Single', year:2021, roles:['Artist'], preview:'hace-tanto-tiempo--luis-guinea--2021.mp3' },
  { title:'Volver a Verte', artist:'Luis Guinea', role:'Artist', artwork:'Volver-a-Verte---Luis-Guinea.webp', releaseType:'Single', year:2020, roles:['Artist'], preview:'volver-a-verte--luis-guinea--2020.mp3' },
  { title:'Cómo Decirte', artist:'Luis Guinea, Pablo Delgado', role:'Producer', artwork:'Cómo-Decirte---Luis-Guinea.webp', releaseType:'Single', year:2022, roles:['Artist', 'Songwriter', 'Producer'], preview:'como-decirte--luis-guinea--2022.mp3' },
  { title:'Nuestro Hogar', artist:'Luis Guinea', role:'Artist', artwork:'Nuestro-Hogar---Luis-Guinea.webp', releaseType:'Single', year:2022, roles:['Artist'], preview:'nuestro-hogar--luis-guinea--2022.mp3' },
  { title:'12 Meses', artist:'Rogelio Edel', role:'Producer', artwork:'12-Meses---Rogelio-Edel.webp', releaseType:'Single', year:2022, roles:['Producer'], preview:'12-meses--rogelio-edel--2022.mp3' },
  { title:'La Bamba', artist:'Rogelio Edel', role:'Producer', artwork:'La-Bamba---Rogelio-Edel.webp', releaseType:'Single', year:2022, roles:['Producer'], preview:'la-bamba--rogelio-edel--2022.mp3' },
  { title:'Abrazo Imaginario', artist:'Ricardo Bojalil', role:'Producer', artwork:'Abrazo-Imaginario---Ricardo-Bojalil.webp', releaseType:'Single', year:2022, roles:['Songwriter', 'Producer', 'Recording Engineer'], preview:'abrazo-imaginario--ricardo-bojalil--2022.mp3' },
  { title:'Allá', artist:'Rogelio Edel', role:'Producer', artwork:'Allá---Rogelio-Edel.webp', releaseType:'Single', year:2022, roles:['Producer'], preview:'alla--rogelio-edel--2022.mp3' },
  { title:'Anoche Me Enamoré', artist:'Rogelio Edel', role:'Producer', artwork:'Anoche-Me-Enamoré---Rogelio-Edel.webp', releaseType:'Single', year:2021, roles:['Producer'], preview:'anoche-me-enamore--rogelio-edel--2021.mp3' },
  { title:'Eres Veneno', artist:'Rogelio Edel', role:'Producer', artwork:'Eres-Veneno---Rogelio-Edel.webp', releaseType:'Single', year:2024, roles:['Producer'], preview:'eres-veneno--rogelio-edel--2024.mp3' },
  { title:'Imagina', artist:'Rogelio Edel', role:'Producer', artwork:'Imagina---Rogelio-Edel.webp', releaseType:'Single', year:2024, roles:['Producer'], preview:'imagina--rogelio-edel--2024.mp3' },
  { title:'Invencible', artist:'Ana Guinea', role:'Producer', artwork:'Invencible---Ana-Guinea.webp', releaseType:'Single', year:2021, roles:['Producer'], preview:'invencible--ana-guinea--2021.mp3' },
  { title:'Si Antes Te Hubiera Conocido - Cover Acústico', artist:'Ana Guinea, Luis Guinea', role:'Producer', artwork:'Si-Antes-Te-Hubiera-Conocido---Cover-Acústico---Ana-Guinea.webp', releaseType:'Single', year:2024, roles:['Producer'], preview:'si-antes-te-hubiera-conocido-cover-acustico--ana-guinea--2024.mp3' },
  { title:'Vida Tras Vida', artist:'Ana Guinea', role:'Producer', artwork:'Vida-Tras-Vida---Ana-Guinea.webp', releaseType:'Single', year:2024, roles:['Producer'], preview:'vida-tras-vida--ana-guinea--2024.mp3' },
  { title:'Volver a Verte', artist:'Ana Guinea', role:'Producer', artwork:'Volver-a-Verte---Ana-Guinea.webp', releaseType:'Single', year:2022, roles:['Producer'], preview:'volver-a-verte--ana-guinea--2022.mp3' }
];
